# Project: FP_114_E1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "../114_1Final_project/final_project5/final_project\ 5.o" ../114_1Final_project/final_project5/poly.o
LINKOBJ  = "../114_1Final_project/final_project5/final_project 5.o" ../114_1Final_project/final_project5/poly.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = FP_114_E1.exe
CXXFLAGS = $(CXXINCS) -std=c99
CFLAGS   = $(INCS) -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

"../114_1Final_project/final_project5/final_project\ 5.o": ../114_1Final_project/final_project5/final_project\ 5.c
	$(CC) -c "../114_1Final_project/final_project5/final_project 5.c" -o "../114_1Final_project/final_project5/final_project 5.o" $(CFLAGS)

../114_1Final_project/final_project5/poly.o: ../114_1Final_project/final_project5/poly.c
	$(CC) -c ../114_1Final_project/final_project5/poly.c -o ../114_1Final_project/final_project5/poly.o $(CFLAGS)
